name: Full Stack CI Pipeline (Next.js + Flask)

on:
  push:
    branches:
      - master
      - zephanj
  pull_request:
    branches:
      - master
      - zephanj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # --- Frontend Setup (Next.js / Node) ---
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Frontend dependencies
      run: |
        npm install

    - name: Build Frontend
      run: |
        npm run build

    # --- Backend Setup (Flask / Python) ---
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Backend dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Backend tests
      run: |
        pip install pytest
        pytest tests/

    # --- SSH Setup ---
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # --- Deploy to EC2 ---
    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Go into project directory
          cd /home/ubuntu/imdb-commitment-issues
          
          # Pull latest code
          git fetch origin master
          git reset --hard origin/master

          # Install/update frontend (Node.js) dependencies
          npm install

          # Build frontend again
          npm run build

          # Install/update backend (Python) dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

          # Kill old Flask backend server if running
          pkill -f "python index.py" || true

          # Kill old Next.js frontend server if running
          pkill -f "node" || true

          # Start Flask backend
          cd /home/ubuntu/imdb-commitment-issues/api
          nohup python3 index.py &

          # Start Next.js frontend
          cd /home/ubuntu/imdb-commitment-issues
          nohup npm run start -- -H 0.0.0.0 -p 3000 &
        EOF
